<template><div class="mv-home"><section class="mv-section"><span class="mv-kicker">WHY MAVERICK</span><h2>AI writes. Engineers decide.</h2><p class="mv-copy">Maverick makes the work around a change visible: the problem, relevant context, plan, evidence, and review decision.</p><div class="mv-grid"><article v-for="card in cards" :key="card.title" class="mv-card"><h3>{{ card.title }}</h3><p>{{ card.copy }}</p></article></div></section><section class="mv-section"><span class="mv-kicker">WORKFLOW / CORE</span><h2>One workflow, any assistant.</h2><div class="mv-workflow" aria-label="Maverick workflow"><div v-for="(step, index) in steps" :key="step" class="mv-step" :class="{ review: step === 'REVIEW' }"><span>0{{ index + 1 }}</span>{{ step }}</div></div></section><section class="mv-section"><span class="mv-kicker">QUICK START</span><h2>First value in a few minutes.</h2><div class="mv-terminal" aria-label="Terminal example using Maverick CLI"><div class="mv-terminal-bar">maverick / project shell</div><pre>$ npx maverick-ai-dev-stack init
✓ project initialized: .maverick/config.json

$ npx maverick-ai-dev-stack task add-pagination
✓ task created: .maverick/tasks/add-pagination

$ npx maverick-ai-dev-stack validate add-pagination
PASS required artefacts and sections are present (warnings may remain).</pre></div></section><section class="mv-section"><span class="mv-kicker">ARTEFACTS</span><h2>Brief. Context. Evidence.</h2><div class="mv-grid"><article v-for="item in artefacts" :key="item.label" class="mv-card"><span class="mv-label">{{ item.label }}</span><h3>{{ item.title }}</h3><p>{{ item.copy }}</p></article></div></section><section class="mv-section"><span class="mv-kicker">ADAPTERS / LAB / OPEN SOURCE</span><h2>Keep the workflow portable.</h2><p class="mv-copy">Claude Code, Codex, Cursor, and generic agents can read the same artefacts. The Lab helps teams test a workflow carefully; it does not manufacture benchmark claims.</p></section></div></template>
<script setup>
const steps = ['BRIEF', 'CONTEXT', 'PLAN', 'BUILD', 'VERIFY', 'REVIEW', 'PR'];
const cards = [{ title: 'Explicit boundaries', copy: 'Small briefs say what changes, what does not, and how completion is verified.' }, { title: 'Inspectable context', copy: 'Targeted paths and local conventions replace repository-wide guessing.' }, { title: 'Human review gate', copy: 'Evidence and the diff support the decision to merge.' }];
const artefacts = [{ label: 'TASK BRIEF', title: 'Scope before code', copy: 'Problem, goal, constraints, and verification make intent reviewable.' }, { label: 'CONTEXT PACK', title: 'Only useful context', copy: 'Architecture, paths, rules, and commands give an agent a bounded start.' }, { label: 'VERIFY / REVIEW', title: 'Evidence before merge', copy: 'Tests, security checks, and a human decision close the loop.' }];
</script>
