import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { commandRegistry } from './command-registry.js';
import { loadConfig } from '../cli.js';
import { presets, requirePreset } from './presets.js';
import { inspectProject } from './project-tools.js';

const exec = promisify(execFile); const ignored = new Set(['node_modules', '.git', 'dist', 'build', 'coverage', '.cache', 'vendor']);
async function text(p) { try { return await readFile(p, 'utf8'); } catch { return ''; } }
async function entries(dir) { try { return await readdir(dir, { withFileTypes: true }); } catch { return []; } }
function section(body, heading) { const match = body.match(new RegExp(`^#{1,4}\\s+${heading.replace(/[.*+?^${}()|[\\]\\]/g, '\\$&')}\\s*\\n([\\s\\S]*?)(?=^#{1,4}\\s|$)`, 'mi')); return match?.[1].trim() || ''; }
function title(body, fallback) { return body.match(/^#\s+(.+)$/m)?.[1]?.replace(/—.*$/, '').trim() || fallback; }
async function walk(root, visitor, depth = 0) { if (depth > 8) return; for (const entry of await entries(root)) { if (ignored.has(entry.name) || (entry.name === 'cache' && root.endsWith('.maverick'))) continue; const path = join(root, entry.name); if (entry.isDirectory()) await walk(path, visitor, depth + 1); else if (entry.isFile()) await visitor(path, entry); } }
async function git(cwd, args) { try { return (await exec('git', args, { cwd })).stdout.trim(); } catch { return ''; } }
export async function buildProjectIndex(cwd) {
  const root = resolve(cwd), [config, project] = await Promise.all([loadConfig(root), inspectProject(root)]);
  const taskBase = join(root, config.taskRoot); const tasks = [];
  for (const entry of await entries(taskBase)) if (entry.isDirectory()) { const dir = join(taskBase, entry.name); const meta = JSON.parse((await text(join(dir, 'TASK.json'))) || '{}'); const taskBody = await text(join(dir, 'TASK.md')); const preset = requirePreset(meta.preset || config.workflow.defaultPreset || 'standard'); const files = (await entries(dir)).filter(x => x.isFile()).map(x => x.name); const reports = files.filter(x => /EVIDENCE|FINDINGS|SECURITY|DEPENDENCY|SCOPE|HANDOFF|READINESS|CHECKPOINT|POLICY/i.test(x)); tasks.push({ id: entry.name, title: title(taskBody, entry.name), preset: preset.id, stages: preset.stages, goal: section(taskBody, 'Goal'), acceptanceCriteria: section(taskBody, 'Acceptance Criteria'), scope: section(taskBody, 'In Scope'), outOfScope: section(taskBody, 'Out of Scope'), verification: section(taskBody, 'Verification'), artifacts: files, reports, validation: files.includes('EVIDENCE.md') ? 'evidence captured' : 'verification pending', updated: (await stat(dir)).mtime.toISOString() }); }
  const docs = []; const modules = []; const adrs = []; const specs = [];
  await walk(root, async path => { const rel = relative(root, path); if (!/\.(md|mdx|txt|js|jsx|ts|tsx)$/i.test(path)) return; const body = await text(path); if (/\.(md|mdx|txt)$/i.test(path)) { const item = { path: rel, title: title(body, rel), excerpt: body.replace(/^---[\s\S]*?---/, '').replace(/\s+/g, ' ').slice(0, 220), content: body, type: /SPEC\.md$/i.test(path) ? 'SPEC' : /(?:^|\/)ADR[-_]?\d|architecture.*decision/i.test(rel) ? 'ADR' : /TASK\.md$/i.test(path) ? 'TASK' : 'DOC' }; docs.push(item); if (item.type === 'SPEC') specs.push({ ...item, status: /FILL ME|TODO/i.test(body) ? 'draft' : 'documented', acceptanceCriteria: section(body, 'Acceptance Criteria'), openQuestions: section(body, 'Open Questions') }); if (item.type === 'ADR') adrs.push(item); } else if (/\.(js|jsx|ts|tsx)$/i.test(path)) { const imports = [...body.matchAll(/(?:from\s*|import\s*\(|require\()\s*['\"]([^'\"]+)['\"]/g)].map(match => match[1]); modules.push({ path: rel, kind: /test|spec/i.test(rel) ? 'test' : 'module', confidence: 'Detected', imports }); } });
  const status = await git(root, ['status', '--short']); const log = await git(root, ['log', '-5', '--pretty=format:%h %s']); const branch = await git(root, ['branch', '--show-current']);
  const adapters = (await entries(join(root, 'adapters'))).filter(x => x.isDirectory()).map(x => ({ id: x.name, status: config.adapter === x.name ? 'active' : 'available' }));
  const agents = (await entries(join(root, 'agents'))).filter(x => x.isFile()).map(x => ({ name: x.name.replace(/^\d+-/, '').replace(/-agent\.md$/, '').replace(/-/g, ' '), path: `agents/${x.name}` }));
  const workflows = (await entries(join(root, 'workflows'))).filter(x => x.isFile()).map(x => ({ name: x.name.replace(/\.md$/, ''), path: `workflows/${x.name}` }));
  const lab = (await entries(join(root, 'lab'))).filter(x => x.isFile()).map(x => ({ name: x.name, path: `lab/${x.name}` }));
  const signals = tasks.flatMap(t => t.validation === 'verification pending' ? [{ level: 'warning', text: `${t.id}: verification evidence is missing.` }] : []).concat(specs.filter(s => /FILL ME|TODO/i.test(s.openQuestions)).map(s => ({ level: 'warning', text: `${s.title}: unresolved questions.` })));
  const couplings = modules.flatMap(module => module.imports.filter(reference => reference.startsWith('.')).map(reference => ({ from: module.path, to: reference, strength: 'static import' })));
  const improvements = [
    ...signals.map((signal, index) => ({ id: `signal-${index}`, title: `Resolve ${signal.text.split(':')[0]}`, detail: signal.text, kind: 'quality', preset: 'strict-review' })),
    ...specs.filter(spec => spec.status === 'draft').map(spec => ({ id: `spec-${spec.path.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}`, title: `Complete specification: ${spec.title}`, detail: 'Unresolved specification content was detected.', kind: 'specification', preset: 'spec-driven' })),
    ...tasks.filter(task => task.validation !== 'evidence captured').map(task => ({ id: `evidence-${task.id}`, title: `Capture verification for ${task.id}`, detail: 'The task has no EVIDENCE.md yet.', kind: 'verification', preset: task.preset || 'standard' }))
  ].slice(0, 12);
  const capabilities = [{ id: 'workflow', name: 'Preset-driven task workflows', category: 'workflow', description: 'Task stages and artifacts are shared with the CLI.', status: 'available', commands: ['task', 'presets', 'validate'] }, { id: 'project-map', name: 'Project intelligence', category: 'project-intelligence', description: 'Package, scripts, instructions and top-level areas.', status: 'available', commands: ['map', 'impact', 'doctor'] }, { id: 'review', name: 'Evidence and review gates', category: 'review', description: 'Verification, scope, security, dependencies and merge readiness.', status: 'available', commands: ['verify', 'review', 'guard', 'security', 'deps', 'readiness'] }, { id: 'governance', name: 'Governance and handoff', category: 'automation', description: 'Policy, handoff, learnings, PR draft and CI generator.', status: 'available', commands: ['policy', 'handoff', 'learn', 'pr', 'ci'] }, { id: 'adapters', name: 'AI adapters', category: 'adapter', description: 'Local adapter templates for supported coding tools.', status: 'available', commands: ['adapter'] }, { id: 'lab', name: 'Maverick Lab', category: 'lab', description: 'Experiments and measurement scorecards.', status: lab.length ? 'available' : 'not configured', commands: [] }];
  return { generatedAt: new Date().toISOString(), project: { ...project, root, version: '1.2.0', activePreset: config.workflow.defaultPreset, activeAdapter: config.adapter, packageManager: project.manifests.includes('package.json') ? 'npm' : 'unknown' }, commands: commandRegistry, presets: Object.values(presets).map(p => ({ ...p, usageCount: tasks.filter(t => t.preset === p.id).length, source: 'built-in' })), tasks, specs, docs, adrs, modules, couplings, improvements, git: { branch: branch || 'not a Git repository', changes: status.split('\n').filter(Boolean), commits: log.split('\n').filter(Boolean) }, adapters, agents, workflows, lab, capabilities, signals };
}
export async function cacheProjectIndex(cwd, index) { const dir = join(cwd, '.maverick', 'cache'); await mkdir(dir, { recursive: true }); const path = join(dir, 'project-index.json'); await writeFile(path, JSON.stringify(index, null, 2)); return path; }
