import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';
import { spawn } from 'node:child_process';

async function exists(path) { try { await access(path); return true; } catch { return false; } }
async function readJson(path) { return JSON.parse(await readFile(path, 'utf8')); }
function commandFor(pkg, name) { return pkg?.scripts?.[name] ? `npm run ${name}` : null; }

export async function inspectProject(cwd) {
  const packagePath = join(cwd, 'package.json');
  const pkg = await exists(packagePath) ? await readJson(packagePath) : null;
  const entries = await readdir(cwd, { withFileTypes: true });
  const directories = entries.filter(entry => entry.isDirectory()).map(entry => entry.name).filter(name => !['node_modules', '.git', '.maverick', 'dist', 'build', 'coverage'].includes(name)).sort();
  const files = entries.filter(entry => entry.isFile()).map(entry => entry.name).sort();
  const manifests = ['package.json', 'pyproject.toml', 'requirements.txt', 'Cargo.toml', 'go.mod', 'pom.xml', 'Gemfile'].filter(name => files.includes(name));
  const commands = ['test', 'lint', 'typecheck', 'build'].map(name => ({ name, command: commandFor(pkg, name) })).filter(item => item.command);
  const candidates = ['AGENTS.md', 'CLAUDE.md', '.github/copilot-instructions.md', 'CONTRIBUTING.md'];
  const instructions = (await Promise.all(candidates.map(async name => (await exists(join(cwd, name))) ? name : null))).filter(Boolean);
  return { name: pkg?.name || cwd.split(/[\\/]/).pop(), manifests, directories, files: files.slice(0, 40), scripts: pkg?.scripts || {}, commands, instructions, language: pkg ? 'JavaScript/TypeScript' : 'unknown', framework: pkg?.dependencies?.react ? 'React' : undefined };
}

export function renderProjectMap(map) {
  const commands = map.commands.length ? map.commands.map(item => `- ${item.name}: \`${item.command}\``).join('\n') : '- No standard npm verification commands detected.';
  return `# Project Map\n\nGenerated by Maverick. Refresh with \`maverick map\`.\n\n## Stack\n- Project: ${map.name}\n- Language: ${map.language}\n- Framework: ${map.framework || 'not detected'}\n- Manifests: ${map.manifests.join(', ') || 'none detected'}\n\n## Top-level areas\n${map.directories.map(name => `- \`${name}/\``).join('\n') || '- none'}\n\n## Verification commands\n${commands}\n\n## Repository instructions\n${map.instructions.map(name => `- \`${name}\``).join('\n') || '- none detected'}\n\n## Context guidance\nRead the nearest instruction file and only the paths relevant to the task before editing.\n`;
}

export async function executeCommand(cwd, command) {
  const [bin, ...args] = command.split(' ');
  return new Promise(resolve => {
    const child = spawn(bin, args, { cwd, shell: false, stdio: ['ignore', 'pipe', 'pipe'] }); let output = '';
    child.stdout.on('data', chunk => { output += chunk; }); child.stderr.on('data', chunk => { output += chunk; });
    child.on('error', error => resolve({ command, ok: false, code: null, output: error.message }));
    child.on('close', code => resolve({ command, ok: code === 0, code, output: output.slice(-12000) }));
  });
}

export async function gitDiff(cwd, against = 'HEAD') {
  const result = await executeCommand(cwd, `git diff ${against} --`);
  return result.ok ? result.output : '';
}

export async function writeEvidence(dir, task, results) {
  await mkdir(dir, { recursive: true });
  const body = `# Verification Evidence — ${task}\n\nGenerated: ${new Date().toISOString()}\n\n${results.map(result => `## ${result.ok ? 'PASS' : 'FAIL'} — ${result.command}\nExit code: ${result.code ?? 'not started'}\n\n\`\`\`text\n${result.output || '(no output)'}\n\`\`\``).join('\n\n')}\n`;
  const path = join(dir, 'EVIDENCE.md'); await writeFile(path, body); return path;
}

export async function changedFiles(cwd, against = 'HEAD') {
  const diff = await gitDiff(cwd, `${against} --name-only`);
  return diff.split('\n').filter(Boolean).map(file => relative(cwd, file));
}

export async function findReferences(cwd, target, maxResults = 40) {
  const needle = target.split('/').pop().replace(/\.[^.]+$/, '');
  const ignored = new Set(['node_modules', '.git', '.maverick', 'dist', 'build', 'coverage']);
  const results = [];
  async function visit(directory) {
    if (results.length >= maxResults) return;
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (results.length >= maxResults || ignored.has(entry.name)) continue;
      const path = join(directory, entry.name);
      if (entry.isDirectory()) await visit(path);
      else if (entry.isFile()) {
        try {
          const text = await readFile(path, 'utf8');
          if (text.includes(needle)) results.push(relative(cwd, path));
        } catch { /* Ignore binary and unreadable files. */ }
      }
    }
  }
  await visit(cwd);
  return results;
}
