import { mkdir, readFile, writeFile, access, copyFile, readdir } from 'node:fs/promises';
import { resolve, dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { createInterface } from 'node:readline/promises';
import { PRESET_IDS, presets, getPreset, requirePreset, stagesForPreset } from './core/presets.js';
import { recommendPreset } from './core/preset-suggestion.js';
import { executeCommand, findReferences, gitDiff, inspectProject, renderProjectMap, writeEvidence } from './core/project-tools.js';
import { commandRegistry } from './core/command-registry.js';
import { startDashboard } from './dashboard/server.js';
async function dashboard(cwd, options = {}) {
  const port = Number(options.port || 4173), host = options.host || '127.0.0.1';
  const server = await startDashboard({ cwd, host, port, watch: !options.noWatch });
  const address = `http://${host}:${port}`;
  if (options.json) output(JSON.stringify({ address, host, port, watch: !options.noWatch }));
  else output(`${brand()} / LENS\n\n✓ project indexed\n✓ tasks indexed\n✓ specs indexed\n✓ docs indexed\n✓ git state indexed\n\nDashboard:\n${address}\n\nLocal only. No project data is uploaded.`);
  if (options.open) { const opener = process.platform === 'darwin' ? 'open' : process.platform === 'win32' ? 'cmd' : 'xdg-open'; try { execFileSync(opener, process.platform === 'win32' ? ['/c', 'start', address] : [address], { stdio: 'ignore' }); } catch { if (options.debug) output('Could not open browser automatically.'); } }
  const close = () => server.close(); process.once('SIGINT', close); process.once('SIGTERM', close);
}
const __dirname = dirname(fileURLToPath(import.meta.url)), root = resolve(__dirname, '..'), slugOk = /^[a-z0-9][a-z0-9-]{1,80}$/;
const defaultConfig = { version: 1, project: { name: '', language: '', framework: '' }, workflow: { requirePlan: true, requireReview: true, requireTests: true, defaultPreset: 'standard' }, adapter: 'generic', taskRoot: '.maverick/tasks', requiredTaskSections: ['Problem', 'Goal', 'Acceptance Criteria', 'In Scope', 'Out of Scope', 'Verification'], requiredContextSections: ['Architecture Summary', 'Relevant Paths', 'Constraints', 'Do Not Touch', 'Commands'] };
async function exists(path) { try { await access(path); return true; } catch { return false; } } async function json(path) { return JSON.parse(await readFile(path, 'utf8')); } function pretty(value) { return `${JSON.stringify(value, null, 2)}\n`; } function rel(cwd, path) { return relative(cwd, path) || '.'; } function output(message) { console.log(message); } function brand() { return process.env.NO_COLOR ? '⚔ MAVERICK' : '\x1b[38;5;208m⚔ MAVERICK\x1b[0m'; }
function mergeConfig(config = {}) { return { ...defaultConfig, ...config, project: { ...defaultConfig.project, ...config.project }, workflow: { ...defaultConfig.workflow, ...config.workflow } }; } async function loadConfig(cwd) { const canonical = join(cwd, '.maverick', 'config.json'), legacy = join(cwd, 'maverick.config.json'); if (await exists(canonical)) return mergeConfig(await json(canonical)); if (await exists(legacy)) return mergeConfig(await json(legacy)); return mergeConfig(); }
function replaceVars(text, vars) { return Object.entries(vars).reduce((s, [k, v]) => s.replaceAll(`{{${k}}}`, v), text); } function sectionPresent(text, name) { const e = name.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); return new RegExp(`^#{1,4}\\s+${e}\\s*$`, 'mi').test(text); } function hasMeaningfulContent(text) { return !/\b(TODO|TBD|FILL ME)\b/i.test(text); } function requireSlug(slug) { if (!slugOk.test(slug || '')) throw new Error('use a lowercase slug such as add-orders-pagination'); }
function parseOptions(args) { const positional = [], options = {}; for (let i = 0; i < args.length; i++) { if (args[i].startsWith('--')) { const key = args[i].slice(2).replace(/-([a-z])/g, (_, c) => c.toUpperCase()); options[key] = args[i + 1]?.startsWith('--') || args[i + 1] === undefined ? true : args[++i]; } else positional.push(args[i]); } return { positional, options }; }
function help() { output(`MAVERICK AI DEV STACK\n\nUsage: maverick <command> [task] [--preset <preset>]\n\nCommands:\n  init                              Initialize .maverick/config.json\n  task <slug> [--preset <preset>]  Create task artefacts\n  map                               Build repository context map\n  packet | run <task> --agent name  Compile a focused agent task packet\n  checkpoint <task>                 Save current diff and Git state\n  verify <task> [--json]            Run detected checks; save EVIDENCE.md\n  security <task>                   Scan changed diff for high-signal risks\n  deps <task>                       Report dependency and lockfile changes\n  review <task> --diff [--against]  Review changed files against task scope\n  pr <task>                         Generate evidence-backed PR draft\n  status [--json]                   Show task stage and pending gates\n  presets [show <preset>]           List or inspect workflow presets\n  suggest [--risk high]             Recommend a preset from local rules\n  validate <slug> [--json]          Validate task artefacts and sections\n  doctor [--fix] | info | version\n\nPreset values: ${PRESET_IDS.join(', ')}\nStandard is the default. Every preset includes human review.`); }
async function chooseDefaultPreset() { if (!process.stdin.isTTY || !process.stdout.isTTY) return 'standard'; output('Choose your default workflow\n1. Standard — Default engineering workflow.\n2. Lightweight — Small, low-risk changes.\n3. Spec Driven — Specification-first for complex work.\n4. Strict Review — Extra verification for high-risk changes.'); const prompt = createInterface({ input: process.stdin, output: process.stdout }); const answer = await prompt.question('Choice [1]: '); prompt.close(); return ({ 1: 'standard', 2: 'lightweight', 3: 'spec-driven', 4: 'strict-review' })[answer.trim() || '1'] || 'standard'; }
async function initProject(cwd) { const dir = join(cwd, '.maverick'), path = join(dir, 'config.json'); if (await exists(path)) throw new Error(`configuration already exists: ${rel(cwd, path)}`); const preset = await chooseDefaultPreset(); await mkdir(dir, { recursive: true }); const name = cwd.split(/[\\/]/).filter(Boolean).pop() || 'my-project'; await writeFile(path, pretty({ ...defaultConfig, workflow: { ...defaultConfig.workflow, defaultPreset: preset }, project: { ...defaultConfig.project, name } })); output(`${brand()}\n✓ project initialized: ${rel(cwd, path)}\nDefault preset: ${getPreset(preset).name}`); }
async function taskPath(cwd, config, slug) { requireSlug(slug); return join(cwd, config.taskRoot, slug); }
async function taskPreset(dir, config) { const meta = join(dir, 'TASK.json'); if (await exists(meta)) return (await json(meta)).preset || config.workflow.defaultPreset; const file = join(dir, 'TASK.md'); if (await exists(file)) { const match = (await readFile(file, 'utf8')).match(/^---\s*\n([\s\S]*?)\n---\s*\n/); const preset = match?.[1].match(/^preset:\s*([^\s#]+)\s*$/m)?.[1]; if (preset) return preset; } return config.workflow.defaultPreset || 'standard'; }
async function createTask(cwd, slug, options = {}) { const config = await loadConfig(cwd), preset = requirePreset(options.preset || config.workflow.defaultPreset || 'standard'), dir = await taskPath(cwd, config, slug); if (await exists(dir)) throw new Error(`task already exists: ${rel(cwd, dir)}; choose another slug or remove it deliberately`); await mkdir(dir, { recursive: true }); const today = new Date().toISOString().slice(0, 10), artifacts = [...preset.artifacts]; if ((options.riskDoc || config.workflow.riskDocumentation) && preset.strict) artifacts.push({ id: 'RISK', file: 'RISK.md', template: 'risk.md', sections: ['Risk Assessment', 'Mitigations', 'Rollback', 'Approval'] }); for (const item of artifacts) await writeFile(join(dir, item.file), replaceVars(await readFile(join(root, 'templates', item.template), 'utf8'), { TASK_SLUG: slug, DATE: today })); await writeFile(join(dir, 'TASK.json'), pretty({ preset: preset.id, createdAt: today })); output(`${brand()}\n✓ task created: ${rel(cwd, dir)}\nPreset: ${preset.name}\nStages: ${preset.stages.map(s => s.toUpperCase()).join(' → ')}`); }
async function getTask(cwd, slug) { const config = await loadConfig(cwd), dir = await taskPath(cwd, config, slug); if (!await exists(dir)) throw new Error(`task not found: ${rel(cwd, dir)}; run maverick task ${slug} first`); return { config, dir, preset: requirePreset(await taskPreset(dir, config)) }; }
async function showArtifact(cwd, slug, filename, label) { const { dir } = await getTask(cwd, slug), path = join(dir, filename); output(`${label}: ${rel(cwd, path)}${await exists(path) ? '' : ' (not included by this preset)'}`); }
async function mapProject(cwd, options = {}) { const map = await inspectProject(cwd), dir = join(cwd, '.maverick', 'context'), path = join(dir, 'PROJECT_MAP.md'); await mkdir(dir, { recursive: true }); await writeFile(path, renderProjectMap(map)); if (options.json) return output(JSON.stringify({ ...map, path: rel(cwd, path) }, null, 2)); output(`${brand()} / MAP\n✓ project map: ${rel(cwd, path)}\nDetected ${map.commands.length} verification command(s) and ${map.directories.length} top-level area(s).`); }
async function taskPacket(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); const mapPath = join(cwd, '.maverick', 'context', 'PROJECT_MAP.md'); const contents = []; for (const file of ['SPEC.md', 'TASK.md', 'CONTEXT.md', 'PLAN.md']) if (await exists(join(dir, file))) contents.push(`## ${file}\n\n${await readFile(join(dir, file), 'utf8')}`); if (await exists(mapPath)) contents.unshift(`## PROJECT_MAP.md\n\n${await readFile(mapPath, 'utf8')}`); const path = join(dir, 'TASK-PACKET.md'); await writeFile(path, `# Maverick Task Packet\n\nPreset: ${preset.name}\nAgent: ${options.agent || 'generic'}\n\nFollow repository instructions, stay in scope, run relevant verification, and leave findings for human review.\n\n${contents.join('\n\n')}`); output(options.json ? JSON.stringify({ preset: preset.id, agent: options.agent || 'generic', path: rel(cwd, path) }) : `${brand()} / PACKET\n✓ agent packet: ${rel(cwd, path)}\nAgent: ${options.agent || 'generic'}`); }
async function verifyTask(cwd, slug, options = {}) { const { config, dir } = await getTask(cwd, slug); const map = await inspectProject(cwd); const configured = config.defaultVerification || []; const commands = map.commands.map(item => item.command).filter(command => !configured.length || configured.some(name => command.endsWith(name))); const selected = commands.length ? commands : map.commands.map(item => item.command); const results = []; for (const command of selected) results.push(await executeCommand(cwd, command)); const evidence = await writeEvidence(dir, slug, results); const payload = { ok: results.every(result => result.ok), results: results.map(result => ({ command: result.command, ok: result.ok, code: result.code })), evidence: rel(cwd, evidence) }; if (options.json) output(JSON.stringify(payload, null, 2)); else { output(`${brand()} / VERIFY`); results.forEach(result => output(`${result.ok ? 'PASS' : 'FAIL'} ${result.command}`)); output(`Evidence: ${payload.evidence}`); } if (!payload.ok) throw new Error('verification failed'); }
async function reviewDiff(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); const diff = await gitDiff(cwd, options.against || 'HEAD'); const files = [...new Set([...diff.matchAll(/^\+\+\+ b\/(.+)$/gm)].map(match => match[1]))]; const findings = []; if (!diff) findings.push('No git diff found against the selected base.'); if (files.some(file => /(^|\/)(\.env|secrets?|credentials?)/i.test(file))) findings.push('Security: sensitive-looking path changed; confirm secrets and PII were not included.'); if (files.some(file => /(?:package-lock|yarn\.lock|pnpm-lock|requirements\.txt|Cargo\.lock)/.test(file))) findings.push('Dependencies: lockfile changed; review new packages, licenses, and vulnerabilities.'); if (preset.strict && !await exists(join(dir, 'EVIDENCE.md'))) findings.push('Strict Review: test evidence is missing; run maverick verify first.'); const path = join(dir, 'REVIEW-FINDINGS.md'); await writeFile(path, `# Diff Review Findings — ${slug}\n\nBase: ${options.against || 'HEAD'}\nChanged files:\n${files.map(file => `- \`${file}\``).join('\n') || '- none'}\n\n## Findings\n${findings.map(finding => `- ${finding}`).join('\n') || '- No automated findings. Complete the human review in REVIEW.md.'}\n`); output(options.json ? JSON.stringify({ files, findings, path: rel(cwd, path) }, null, 2) : `${brand()} / REVIEW\nChanged files: ${files.length}\nFindings: ${findings.length}\nReport: ${rel(cwd, path)}`); }
async function checkpoint(cwd, slug, options = {}) { const { dir } = await getTask(cwd, slug); const [status, diff] = await Promise.all([executeCommand(cwd, 'git status --short'), gitDiff(cwd, options.against || 'HEAD')]); const path = join(dir, 'CHECKPOINT.md'); await writeFile(path, `# Checkpoint — ${slug}\n\nCreated: ${new Date().toISOString()}\nBase: ${options.against || 'HEAD'}\n\n## Git status\n\`\`\`text\n${status.output || '(unavailable)'}\n\`\`\`\n\n## Diff\n\`\`\`diff\n${diff || '(no diff available)'}\n\`\`\`\n`); output(options.json ? JSON.stringify({ path: rel(cwd, path), gitAvailable: status.ok }) : `${brand()} / CHECKPOINT\n✓ saved: ${rel(cwd, path)}`); }
async function impact(cwd, path, options = {}) { if (!path || path.includes('..')) throw new Error('provide a project-relative file path'); const references = await findReferences(cwd, path); const payload = { path, references, count: references.length, truncated: references.length === 40 }; output(options.json ? JSON.stringify(payload, null, 2) : `${brand()} / IMPACT\nTarget: ${path}\nReferences:\n${references.map(file => `- ${file}`).join('\n') || '- none found'}`); }
async function guardScope(cwd, slug, options = {}) { const { config, dir } = await getTask(cwd, slug); const task = await readFile(join(dir, 'TASK.md'), 'utf8'); const diff = await gitDiff(cwd, options.against || 'HEAD'); const changed = [...new Set([...diff.matchAll(/^\+\+\+ b\/(.+)$/gm)].map(match => match[1]))]; const expected = (task.match(/^## Expected Changed Files\n([\s\S]*?)(?=^## |$)/m)?.[1].match(/`([^`]+)`/g) || []).map(value => value.slice(1, -1)).filter(value => !/FILL ME/i.test(value)); const outsideScope = expected.length ? changed.filter(file => !expected.includes(file)) : []; const maxFiles = config.maxChangedFilesGuideline || 8; const findings = [changed.length > maxFiles ? `Change budget exceeded: ${changed.length}/${maxFiles} files.` : null, ...outsideScope.map(file => `Not listed in Expected Changed Files: ${file}`)].filter(Boolean); const report = join(dir, 'SCOPE-GUARD.md'); await writeFile(report, `# Scope Guard — ${slug}\n\nChanged files: ${changed.length}\nExpected files: ${expected.length || 'not specified'}\n\n## Findings\n${findings.map(finding => `- ⚠ ${finding}`).join('\n') || '- Within configured scope guard.'}\n`); const payload = { ok: findings.length === 0, changed, expected, findings, path: rel(cwd, report) }; output(options.json ? JSON.stringify(payload, null, 2) : `${brand()} / GUARD\n${payload.ok ? 'PASS' : 'WARN'} ${findings.length} finding(s)\nReport: ${payload.path}`); if (!payload.ok) throw new Error('scope guard requires human review'); }
async function learn(cwd, slug, options = {}) { await getTask(cwd, slug); if (!options.rule || options.rule === true) throw new Error('provide a rule with --rule "..."'); const dir = join(cwd, '.maverick'), path = join(dir, 'LEARNINGS.md'); await mkdir(dir, { recursive: true }); const existing = await exists(path) ? await readFile(path, 'utf8') : '# Maverick Learnings\n\nProposed reusable rules. Promote only after team review.\n'; await writeFile(path, `${existing}\n- [ ] ${options.rule}\n  - Source task: \`${slug}\`\n`); output(options.json ? JSON.stringify({ path: rel(cwd, path), rule: options.rule }) : `${brand()} / LEARN\n✓ proposed rule saved: ${rel(cwd, path)}`); }
async function handoff(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); const present = {}; for (const file of ['EVIDENCE.md', 'REVIEW-FINDINGS.md', 'SECURITY-REPORT.md', 'DEPENDENCY-REVIEW.md', 'SCOPE-GUARD.md', 'CHECKPOINT.md']) present[file] = await exists(join(dir, file)); const task = await readFile(join(dir, 'TASK.md'), 'utf8'); const goal = task.match(/^## Goal\n([^\n]*)/m)?.[1].trim() || 'See TASK.md.'; const remaining = Object.entries(present).filter(([, value]) => !value).map(([file]) => file); const path = join(dir, 'HANDOFF.md'); await writeFile(path, `# Handoff — ${slug}\n\n## Goal\n${goal}\n\n## Workflow\nPreset: ${preset.name}\n\n## Completed evidence\n${Object.entries(present).filter(([, value]) => value).map(([file]) => `- \`${file}\``).join('\n') || '- none'}\n\n## Still needed\n${remaining.map(file => `- \`${file}\``).join('\n') || '- Complete human review and PR decision.'}\n\n## Next owner\nName/agent: ${options.to || 'FILL ME'}\n\n## Notes\nRead TASK.md, CONTEXT.md, and the reports listed above before continuing.\n`); output(options.json ? JSON.stringify({ path: rel(cwd, path), remaining }) : `${brand()} / HANDOFF\n✓ handoff: ${rel(cwd, path)}\nRemaining reports: ${remaining.length}`); }
async function readiness(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); const required = ['EVIDENCE.md', 'REVIEW-FINDINGS.md', 'SECURITY-REPORT.md', 'DEPENDENCY-REVIEW.md', 'SCOPE-GUARD.md']; if (preset.strict) required.push('CHECKPOINT.md'); const available = []; const missing = []; for (const file of required) (await exists(join(dir, file)) ? available : missing).push(file); const review = await exists(join(dir, 'REVIEW.md')) ? await readFile(join(dir, 'REVIEW.md'), 'utf8') : ''; const decisionMade = /- \[[xX]\] (?:approve|approve with follow-up|request changes)/.test(review); if (!decisionMade) missing.push('Human decision in REVIEW.md'); const ready = missing.length === 0; const path = join(dir, 'MERGE-READINESS.md'); await writeFile(path, `# Merge Readiness — ${slug}\n\nPreset: ${preset.name}\nStatus: ${ready ? 'READY FOR HUMAN MERGE DECISION' : 'NOT READY'}\n\n## Available gates\n${available.map(file => `- ✓ \`${file}\``).join('\n') || '- none'}\n\n## Outstanding gates\n${missing.map(file => `- ! ${file}`).join('\n') || '- none'}\n\nMaverick does not merge code. A human remains accountable for the final decision.\n`); const payload = { ready, available, missing, path: rel(cwd, path) }; output(options.json ? JSON.stringify(payload, null, 2) : `${brand()} / READINESS\n${ready ? 'READY' : 'NOT READY'}\nOutstanding gates: ${missing.length}\nReport: ${payload.path}`); if (!ready) throw new Error('merge readiness gates are incomplete'); }
async function policy(cwd, action, slug, options = {}) { const dir = join(cwd, '.maverick'), path = join(dir, 'policy.json'); if (action === 'init') { if (await exists(path)) throw new Error(`policy already exists: ${rel(cwd, path)}`); await mkdir(dir, { recursive: true }); await writeFile(path, await readFile(join(root, 'templates', 'policy.json'), 'utf8')); return output(`${brand()} / POLICY\n✓ policy created: ${rel(cwd, path)}`); } if (!await exists(path)) throw new Error('policy not found; run maverick policy init'); const rules = await json(path); if (action === 'show') return output(options.json ? JSON.stringify(rules, null, 2) : `${brand()} / POLICY\n${pretty(rules)}`); if (action !== 'check') throw new Error('use policy init, policy show, or policy check <task>'); const { dir: taskDir, preset } = await getTask(cwd, slug); const diff = await gitDiff(cwd, options.against || 'HEAD'); const changed = [...new Set([...diff.matchAll(/^\+\+\+ b\/(.+)$/gm)].map(match => match[1]))]; const sensitive = changed.filter(file => rules.sensitivePaths.some(prefix => file.includes(prefix))); const findings = []; if (changed.length > (rules.maxChangedFiles || Infinity)) findings.push(`Changed ${changed.length} files; policy maximum is ${rules.maxChangedFiles}.`); if (sensitive.length && preset.id !== rules.requiredPresetForSensitivePaths) findings.push(`Sensitive paths require preset ${rules.requiredPresetForSensitivePaths}: ${sensitive.join(', ')}.`); const report = join(taskDir, 'POLICY-CHECK.md'); await writeFile(report, `# Policy Check — ${slug}\n\nPolicy: ${rel(cwd, path)}\n\n## Sensitive changed paths\n${sensitive.map(file => `- \`${file}\``).join('\n') || '- none'}\n\n## Findings\n${findings.map(finding => `- ⚠ ${finding}`).join('\n') || '- Policy satisfied.'}\n`); const payload = { ok: findings.length === 0, changed, sensitive, findings, path: rel(cwd, report) }; output(options.json ? JSON.stringify(payload, null, 2) : `${brand()} / POLICY CHECK\n${payload.ok ? 'PASS' : 'WARN'} ${findings.length} finding(s)\nReport: ${payload.path}`); if (!payload.ok) throw new Error('policy check requires human review'); }
async function adapter(cwd, action, name, options = {}) { const adapters = { codex: ['adapters/codex/AGENTS.md.example', 'AGENTS.md'], 'claude-code': ['adapters/claude-code/CLAUDE.md.example', 'CLAUDE.md'], cursor: ['adapters/cursor/maverick.mdc.example', '.cursor/rules/maverick.mdc'], generic: ['adapters/generic/ROLE_PROMPT.txt', '.maverick/ROLE_PROMPT.txt'] }; if (action === 'list') return output(options.json ? JSON.stringify(Object.keys(adapters)) : `${brand()} / ADAPTERS\n${Object.keys(adapters).join('\n')}`); if (action !== 'install' || !adapters[name]) throw new Error(`use adapter list or adapter install <${Object.keys(adapters).join('|')}>`); const [source, target] = adapters[name], destination = join(cwd, target); if (await exists(destination)) throw new Error(`adapter target already exists: ${rel(cwd, destination)}`); await mkdir(dirname(destination), { recursive: true }); await copyFile(join(root, source), destination); output(options.json ? JSON.stringify({ adapter: name, path: rel(cwd, destination) }) : `${brand()} / ADAPTER\n✓ ${name}: ${rel(cwd, destination)}`); }
async function ci(cwd, provider, slug, options = {}) { if (provider !== 'github') throw new Error('only the github CI generator is currently available'); await getTask(cwd, slug); const destination = join(cwd, '.github', 'workflows', `maverick-${slug}.yml`); if (await exists(destination)) throw new Error(`CI workflow already exists: ${rel(cwd, destination)}`); await mkdir(dirname(destination), { recursive: true }); const content = replaceVars(await readFile(join(root, 'templates', 'github-actions-maverick.yml'), 'utf8'), { TASK_SLUG: slug }); await writeFile(destination, content); output(options.json ? JSON.stringify({ provider, task: slug, path: rel(cwd, destination) }) : `${brand()} / CI\n✓ GitHub Actions workflow: ${rel(cwd, destination)}`); }
async function securityScan(cwd, slug, options = {}) { const { dir } = await getTask(cwd, slug); const diff = await gitDiff(cwd, options.against || 'HEAD'); const rules = [{ name: 'Private key material', pattern: /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/ }, { name: 'Likely cloud/API secret assignment', pattern: /(?:api[_-]?key|secret|token|password)\s*[:=]\s*['"][^'"\s]{12,}/i }, { name: 'Potentially unsafe dynamic execution', pattern: /(?:eval\(|child_process\.exec\(|shell:\s*true)/ }]; const findings = rules.filter(rule => rule.pattern.test(diff)).map(rule => rule.name); const path = join(dir, 'SECURITY-REPORT.md'); await writeFile(path, `# Security Scan — ${slug}\n\nBase: ${options.against || 'HEAD'}\n\n## Automated signals\n${findings.map(finding => `- ⚠ ${finding}`).join('\n') || '- No high-signal patterns found in the current diff.'}\n\n## Human checks\n- [ ] Authorization and trust boundaries reviewed\n- [ ] No secrets, PII, or production credentials added\n- [ ] New dependencies and network access reviewed\n`); const payload = { findings, path: rel(cwd, path) }; output(options.json ? JSON.stringify(payload, null, 2) : `${brand()} / SECURITY\nSignals: ${findings.length}\nReport: ${payload.path}`); if (findings.length) throw new Error('security signals require human review'); }
async function dependencyReview(cwd, slug, options = {}) { const { dir } = await getTask(cwd, slug); const diff = await gitDiff(cwd, options.against || 'HEAD'); const lockfiles = [...new Set([...diff.matchAll(/^\+\+\+ b\/(.*(?:package-lock\.json|yarn\.lock|pnpm-lock\.yaml|requirements\.txt|poetry\.lock|Cargo\.lock))$/gm)].map(match => match[1]))]; const manifests = [...new Set([...diff.matchAll(/^\+\+\+ b\/(.*(?:package\.json|pyproject\.toml|go\.mod|Cargo\.toml))$/gm)].map(match => match[1]))]; const path = join(dir, 'DEPENDENCY-REVIEW.md'); await writeFile(path, `# Dependency Review — ${slug}\n\n## Changed manifests\n${manifests.map(file => `- \`${file}\``).join('\n') || '- none'}\n\n## Changed lockfiles\n${lockfiles.map(file => `- \`${file}\``).join('\n') || '- none'}\n\n## Human checks\n- [ ] New packages are necessary and maintained.\n- [ ] License and vulnerability impact were reviewed.\n- [ ] Lockfile changes match intended manifest changes.\n`); output(options.json ? JSON.stringify({ manifests, lockfiles, path: rel(cwd, path) }, null, 2) : `${brand()} / DEPENDENCIES\nManifests: ${manifests.length}; lockfiles: ${lockfiles.length}\nReport: ${rel(cwd, path)}`); }
async function draftPr(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); const task = await readFile(join(dir, 'TASK.md'), 'utf8'); const evidence = await exists(join(dir, 'EVIDENCE.md')) ? await readFile(join(dir, 'EVIDENCE.md'), 'utf8') : 'Verification evidence has not been captured.'; const findings = await exists(join(dir, 'REVIEW-FINDINGS.md')) ? 'Diff review report is available in REVIEW-FINDINGS.md.' : 'Diff review has not been run.'; const goal = task.match(/^## Goal\n([^\n]*)/m)?.[1].trim() || 'See TASK.md.'; const path = join(dir, 'PR-DRAFT.md'); await writeFile(path, `# PR Draft — ${slug}\n\n## Summary\n${goal}\n\n## Workflow\nPreset: ${preset.name}\n\n## Verification\n${evidence.includes('## PASS') ? 'Automated verification evidence captured in EVIDENCE.md.' : evidence}\n\n## Review\n${findings}\n\n## Risks / rollback\nSee TASK.md and PLAN.md.\n\n## Human Review\n- [ ] Scope, behavior, tests, and security-sensitive decisions reviewed.\n`); output(options.json ? JSON.stringify({ path: rel(cwd, path) }) : `${brand()} / PR\n✓ draft: ${rel(cwd, path)}`); }
function validatorArtifacts(preset, riskDoc) { const items = preset.artifacts.map(item => ({ ...item, sections: preset.strict && item.id === 'TASK' ? [...item.sections, 'Risk', 'Expected Changed Files', 'Actual Changed Files'] : preset.strict && item.id === 'PLAN' ? [...item.sections, 'Rollback'] : preset.strict && item.id === 'REVIEW' ? ['Scope', 'Behavior', 'Tests', 'Security', 'Reliability', 'Observability', 'Dependencies', 'Rollback', 'Maintainability', 'Final Decision'] : item.sections })); return riskDoc ? [...items, { id: 'RISK', file: 'RISK.md', sections: ['Risk Assessment', 'Mitigations', 'Rollback', 'Approval'] }] : items; }
async function validate(cwd, slug, options = {}) { const { dir, preset } = await getTask(cwd, slug); let errors = 0, warnings = 0; const results = []; for (const item of validatorArtifacts(preset, await exists(join(dir, 'RISK.md')))) { const path = join(dir, item.file); if (!await exists(path)) { results.push({ file: item.file, status: 'FAIL', message: 'missing' }); errors++; continue; } const text = await readFile(path, 'utf8'); for (const section of item.sections) if (!sectionPresent(text, section)) { results.push({ file: item.file, status: 'FAIL', message: `missing section "${section}"` }); errors++; } if (!hasMeaningfulContent(text)) { results.push({ file: item.file, status: 'WARN', message: 'placeholders remain' }); warnings++; } } if (options.json) output(JSON.stringify({ preset: preset.id, stages: preset.stages, valid: !errors, errors, warnings, results }, null, 2)); else { output(`${brand()} / VALIDATE\nPreset: ${preset.name}`); results.forEach(r => output(`${r.status} ${r.file}: ${r.message}`)); if (!errors) output(`PASS required artefacts and sections are present${warnings ? ` (${warnings} warning(s))` : ''}.`); } if (errors) throw new Error(`${errors} validation error(s)`); }
function showPresets(id) { if (id) { const p = requirePreset(id); return output(`${brand()} / PRESET\n\nPreset:\n${p.name}\n\nArtifacts:\n${p.artifacts.map(a => a.id).join('\n')}\n\nStages:\n${p.stages.map(s => s.toUpperCase()).join(' → ')}\n\nBest for:\n${p.bestFor}`); } output(`${brand()} / PRESETS\n\n${Object.values(presets).map(p => `${p.id.toUpperCase()}\n${p.description}`).join('\n\n')}`); }
async function status(cwd, options = {}) { const config = await loadConfig(cwd), base = join(cwd, config.taskRoot); if (!await exists(base)) return output(options.json ? '[]' : 'No tasks yet. Run maverick task add-your-feature.'); const tasks = []; for (const entry of (await readdir(base, { withFileTypes: true })).filter(d => d.isDirectory()).sort((a, b) => a.name.localeCompare(b.name))) { const dir = join(base, entry.name), preset = await taskPreset(dir, config); const evidence = await exists(join(dir, 'EVIDENCE.md')), findings = await exists(join(dir, 'REVIEW-FINDINGS.md')); tasks.push({ task: entry.name, preset, evidence, findings, next: evidence ? (findings ? 'complete human review' : 'run review --diff') : 'run verify' }); } output(options.json ? JSON.stringify(tasks, null, 2) : tasks.map(task => `${task.task}\t${task.preset}\t${task.next}`).join('\n')); } function gitAvailable() { try { execFileSync('git', ['--version'], { stdio: 'ignore' }); return true; } catch { return false; } } async function doctor(cwd, options = {}) { const config = await loadConfig(cwd), map = await inspectProject(cwd); const checks = [['Node >= 20', Number(process.versions.node.split('.')[0]) >= 20], ['Git available', gitAvailable()], ['Git repository', await exists(join(cwd, '.git'))], ['Repository instructions', map.instructions.length > 0], ['Verification scripts', map.commands.length > 0]]; const fixes = checks.filter(([, ok]) => !ok).map(([name]) => `Add or configure: ${name}`); if (options.json) return output(JSON.stringify({ checks: checks.map(([name, ok]) => ({ name, ok })), fixes }, null, 2)); for (const [name, ok] of checks) output(`${ok ? 'PASS' : 'WARN'} ${name}`); if (options.fix) output(`Suggested fixes:\n${fixes.map(fix => `- ${fix}`).join('\n') || '- No fixes needed.'}`); output(`Default preset: ${config.workflow.defaultPreset}\nNo telemetry is collected by Maverick.`); } function info() { output('Maverick AI Dev Stack\nVersion 1.0.0\nA vendor-neutral engineering workflow. No telemetry by default.'); }
export async function main(args, cwd = process.cwd()) {
  const { positional, options } = parseOptions(args), [command, arg, third] = positional;
  if (!command || ['help', '--help', '-h'].includes(command)) return help();
  if (['dashboard', 'dash', 'lens'].includes(command)) return dashboard(cwd, options);
  if (command === 'init') return arg ? createTask(cwd, arg, options) : initProject(cwd);
  if (['task', 'create'].includes(command)) return createTask(cwd, arg, options);
  if (command === 'map') return mapProject(cwd, options); if (['packet', 'run'].includes(command)) return taskPacket(cwd, arg, options);
  if (command === 'checkpoint') return checkpoint(cwd, arg, options); if (command === 'impact') return impact(cwd, arg, options);
  if (command === 'guard') return guardScope(cwd, arg, options); if (command === 'learn') return learn(cwd, arg, options);
  if (command === 'handoff') return handoff(cwd, arg, options); if (command === 'readiness') return readiness(cwd, arg, options);
  if (command === 'policy') return policy(cwd, arg, third, options); if (command === 'adapter') return adapter(cwd, arg, third, options); if (command === 'ci') return ci(cwd, arg, third, options);
  if (command === 'verify') return verifyTask(cwd, arg, options); if (command === 'security') return securityScan(cwd, arg, options); if (command === 'deps') return dependencyReview(cwd, arg, options); if (command === 'pr') return draftPr(cwd, arg, options);
  if (command === 'presets') return showPresets(arg === 'show' ? third : undefined); if (command === 'suggest') { const rec = recommendPreset(options); return output(options.json ? JSON.stringify(rec) : `Recommended preset: ${getPreset(rec.preset).name}\nReason: ${rec.reason}`); }
  if (command === 'validate') return validate(cwd, arg, options); if (command === 'context') return showArtifact(cwd, arg, 'CONTEXT.md', 'Context'); if (command === 'plan') return showArtifact(cwd, arg, 'PLAN.md', 'Plan');
  if (command === 'review') return options.diff ? reviewDiff(cwd, arg, options) : showArtifact(cwd, arg, 'REVIEW.md', 'Review'); if (command === 'doctor') return doctor(cwd, options); if (command === 'status') return status(cwd, options);
  if (['info', 'version', '--version', '-v'].includes(command)) return info(); throw new Error(`unknown command: ${command}; run maverick help`);
}
export { sectionPresent, replaceVars, loadConfig, defaultConfig, stagesForPreset, recommendPreset, commandRegistry };
